### ISSUE TITLE
I should be able to put my license checker config in another json file

### ISSUE THREAD

**Issue by awjh** [awjh/license-check-and-add#8]
The license checker should allow config to be written in an external file to prevent cluttering of the package.json

**Comment by hcsalis** [comment]
Hello @awjh, 

I also have a suggestion regarding config files. We have 2 different use cases to run this tool: one for checking licenses in source files in /src folder and another for inserting licenses to generated bundles in /dist folder. In addition to a default config file at the project root, it would be great to have an option to pass a config json file to the script with an argument like "-c" or "--config", similar to jest or other tools so that we can utilize this library with two different npm scripts. We currently have a hacky script to achieve this. An ideal use case would be like the following.

```json
{
  "scripts": {
    "license:default": "npm run license-check-and-add",
    "license:check-src": "npm run license-check-and-add -c license-check-src-config.json",
    "license:insert-dist": "npm run license-check-and-add -c license-insert-dist-config.json",
  } 
}
```

**Comment by awjh** [comment]
Resolved in V3
